videos:
  # Loudenvielle 2025
  - riderId: "amaury_pierron"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=jUfJyZFpAoY&t=63s&ab_channel=GoProBike"
    splits:
      - "00:01:15"
      - "00:39:19"
      - "01:35:08"
      - "02:36:04"
      - "02:58:24"
      - "03:17:00"
  - riderId: "vali_holl"
    trackId: "loudenvielle_2025"
    url: "https://youtu.be/AClbgHAvAZ4?si=jNAzrUfA6t9s9nY7"
    splits:
      - "00:01:15"
      - "00:43:21"
      - "01:46:01"
      - "02:56:20"
      - "03:24:00"
      - "03:45:07"
  - riderId: "jackson_goldstone"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=luP751orGiA&ab_channel=GoProBike"
    splits:
      - "00:01:05"
      - "00:41:11"
      - "01:40:03"
      - "02:41:10"
      - "03:03:10"
      - "03:21:17"
  - riderId: "gracey_hemstreet"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=MYs81d9h4lw&ab_channel=GoProBike"
    splits:
      - "00:02:12"
      - "00:47:13"
      - "01:49:07"
      - "02:58:16"
      - "03:23:11"
      - "03:42:18"
  - riderId: "joe_breeden"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=CaDmwKk-HWg&ab_channel=GoProBike"
    splits:
      - "00:01:02"
      - "00:39:20"
      - "01:37:16"
      - "02:39:08"
      - "03:02:21"
      - "03:21:12"
  # Poland 2025
  - riderId: "max_alran"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=2jhdCTKWw5g&ab_channel=GoProBike"
    splits:
      - "00:01:14"
      - "00:43:03"
      - "01:32:18"
      - "01:58:16"
      - "02:44:15"
      - "03:10:07"
  - riderId: "oisin_o_callaghan"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=DiYvhgRVygQ"
    splits:
      - "00:00:17"
      - "00:42:12"
      - "01:32:07"
      - "01:57:23"
      - "02:41:15"
      - "03:06:08"
  - riderId: "vali_holl"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=eXR-dyW3fV8&ab_channel=GoProBike"
    splits:
      - "00:00:15"
      - "00:50:00"
      - "01:47:14"
      - "02:18:19"
      - "03:09:18"
      - "03:40:15"
  - riderId: "asa_vermette"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=9xnRXNqGq2s&ab_channel=GoProBike"
    splits:
      - "00:00:12"
      - "00:42:22"
      - "01:32:09"
      - "01:57:20"
      - "02:40:19"
      - "03:05:13"
  - riderId: "nina_hoffman"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=PSAw-_daUO4&ab_channel=GoProBike"
    splits:
  # Leogang 2025
  - riderId: "jackson_goldstone"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=rujzaUCp70A&ab_channel=GoProBike"
    splits:
  - riderId: "laurie_greenland"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=nw-Bx_ZZ0dE&ab_channel=GoProBike"
    splits:
  - riderId: "vali_holl"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=LG2clYbyhxs&ab_channel=GoProBike"
    splits:
  - riderId: "jordan_williams"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=Sut_6oBJrQU&ab_channel=GoProBike"
    splits:
  - riderId: "asa_vermette"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=65VYZWVdrTU&ab_channel=GoProBike"
    splits:
  # Mont Sainte Anne 2024
  - riderId: "troy_brosnan"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=162sGhCWAyE&ab_channel=GoProBike"
    splits:
  - riderId: "max_alran"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=uqXWH5uIPHU&ab_channel=GoProBike"
    splits:
  - riderId: "loic_bruna"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=PVHPW0npwrU&t=16s&ab_channel=GoProBike"
    splits:
  - riderId: "lachlan_stevens_mcnab"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=MzY2NPYRbPU&ab_channel=GoProBike"
    splits:
  - riderId: "jackson_goldstone"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=xJuvF-O04qQ&ab_channel=WHOOPUCIMountainBikeWorldSeries"
    splits:
  # Val Di Sole 2024
  - riderId: "amaury_pierron"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=Tigbxbtw-VE&ab_channel=GoProBike"
    splits:
  - riderId: "loic_bruna"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=weoP8SIQf4I&ab_channel=GoProBike"
    splits:
  - riderId: "myriam_nicole"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=wxmaA02ymB4&ab_channel=GoProBike"
    splits:
  - riderId: "dakota_norton"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=0_TDGoLdCqw&ab_channel=GoProBike"
    splits:
  - riderId: "loris_vergier"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=l9fhFQYd6N8&ab_channel=GoProBike"
    splits: