videos:
  # Loudenvielle 2025
  - riderId: "amaury_pierron"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=jUfJyZFpAoY&t=63s&ab_channel=GoProBike"
    splits:
      - "00:01:15"
      - "00:39:19"
      - "01:35:08"
      - "02:36:04"
      - "02:58:24"
      - "03:17:06"
  - riderId: "vali_holl"
    trackId: "loudenvielle_2025"
    url: "https://youtu.be/AClbgHAvAZ4?si=jNAzrUfA6t9s9nY7"
    splits:
      - "00:01:15"
      - "00:43:21"
      - "01:46:01"
      - "02:56:20"
      - "03:24:00"
      - "03:45:07"
  - riderId: "jackson_goldstone"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=luP751orGiA&ab_channel=GoProBike"
    splits:
      - "00:01:05"
      - "00:41:11"
      - "01:40:03"
      - "02:41:10"
      - "03:03:10"
      - "03:21:17"
  - riderId: "gracey_hemstreet"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=MYs81d9h4lw&ab_channel=GoProBike"
    splits:
      - "00:02:12"
      - "00:46:07"
      - "01:48:02"
      - "02:57:11"
      - "03:22:06"
      - "03:41:13"
  - riderId: "joe_breeden"
    trackId: "loudenvielle_2025"
    url: "https://www.youtube.com/watch?v=CaDmwKk-HWg&ab_channel=GoProBike"
    splits:
      - "00:01:02"
      - "00:39:20"
      - "01:37:16"
      - "02:39:08"
      - "03:02:21"
      - "03:21:11"
  # Poland 2025
  - riderId: "max_alran"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=2jhdCTKWw5g&ab_channel=GoProBike"
    splits:
      - "00:01:14"
      - "00:43:03"
      - "01:32:18"
      - "01:58:16"
      - "02:44:15"
      - "03:10:07"
  - riderId: "oisin_o_callaghan"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=DiYvhgRVygQ"
    splits:
      - "00:00:17"
      - "00:42:12"
      - "01:32:07"
      - "01:57:23"
      - "02:41:15"
      - "03:06:08"
  - riderId: "vali_holl"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=eXR-dyW3fV8&ab_channel=GoProBike"
    splits:
      - "00:00:15"
      - "00:50:00"
      - "01:47:14"
      - "02:18:19"
      - "03:09:18"
      - "03:40:15"
  - riderId: "asa_vermette"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=9xnRXNqGq2s&ab_channel=GoProBike"
    splits:
      - "00:00:12"
      - "00:42:22"
      - "01:32:09"
      - "01:57:20"
      - "02:40:19"
      - "03:05:13"
  - riderId: "nina_hoffman"
    trackId: "poland_2025"
    url: "https://www.youtube.com/watch?v=PSAw-_daUO4&ab_channel=GoProBike"
    splits:
      - "00:01:20"
      - "00:51:00"
      - "01:49:21"
      - "02:20:18"
      - "03:11:06"
      - "03:41:17"
  # Leogang 2025
  - riderId: "laurie_greenland"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=nw-Bx_ZZ0dE&ab_channel=GoProBike"
    splits:
      - "00:01:08"
      - "00:32:15"
      - "01:18:08"
      - "01:57:00"
      - "02:34:09"
      - "03:05:21"
  - riderId: "vali_holl"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=LG2clYbyhxs&ab_channel=GoProBike"
    splits:
      - "00:00:22"
      - "00:35:23"
      - "01:28:00"
      - "02:10:12"
      - "02:54:20"
      - "03:29:13"
  - riderId: "jordan_williams"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=Sut_6oBJrQU&ab_channel=GoProBike"
    splits:
      - "00:00:22"
      - "00:32:09"
      - "01:17:06"
      - "01:56:06"
      - "02:33:18"
      - "03:04:07"
  - riderId: "asa_vermette"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=65VYZWVdrTU&ab_channel=GoProBike"
    splits:
       - "00:01:15"
       - "00:33:15"
       - "01:20:22"
       - "01:58:11"
       - "02:36:18"
       - "03:08:00"
  - riderId: "gracey_hemstreet"
    trackId: "leogang_2025"
    url: "https://www.youtube.com/watch?v=zaf8OvA7X68&ab_channel=GoProBike"
    splits:
       - "00:02:02"
       - "00:36:02"
       - "01:27:14"
       - "02:09:04"
       - "02:50:03"
       - "03:23:12"
  # Mont Sainte Anne 2024
  - riderId: "troy_brosnan"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=162sGhCWAyE&ab_channel=GoProBike"
    splits:
      - "00:01:07"
      - "00:42:13"
      - "01:43:20"
      - "02:29:21"
      - "03:21:15"
      - "03:44:04"
  - riderId: "max_alran"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=uqXWH5uIPHU&ab_channel=GoProBike"
    splits:
      - "00:01:08"
      - "00:44:21"
      - "01:49:22"
      - "02:36:23"
      - "03:31:16"
      - "03:55:10"
  - riderId: "loic_bruni"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=PVHPW0npwrU&t=16s&ab_channel=GoProBike"
    splits:
      - "00:00:20"
      - "00:42:16"
      - "01:43:19"
      - "02:29:16"
      - "03:23:09"
      - "03:46:23"
  - riderId: "lachlan_stevens_mcnab"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=MzY2NPYRbPU&ab_channel=GoProBike"
    splits:
      - "00:00:20"
      - "00:44:22"
      - "01:50:15"
      - "02:37:22"
      - "03:32:13"
      - "03:55:17"
  - riderId: "vali_holl"
    trackId: "mont_sainte_anne_2024"
    url: "https://www.youtube.com/watch?v=cC9npVSU1gM"
    splits:
      - "00:00:15"
      - "00:47:18"
      - "02:03:15"
      - "02:59:03"
      - "04:05:15"
      - "04:31:09"
  # Val Di Sole 2024
  - riderId: "amaury_pierron"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=Tigbxbtw-VE&ab_channel=GoProBike"
    splits:
      - "00:01:09"
      - "00:49:12"
      - "01:46:18"
      - "02:33:02"
      - "03:07:02"
      - "03:41:08"
  - riderId: "loic_bruni"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=weoP8SIQf4I&ab_channel=GoProBike"
    splits:
      - "00:00:14"
      - "00:50:04"
      - "01:50:18"
      - "02:38:11"
      - "03:13:19"
      - "03:48:20"
  - riderId: "dakota_norton"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=0_TDGoLdCqw&ab_channel=GoProBike"
    splits:
      - "00:00:19"
      - "00:50:14"
      - "01:50:22"
      - "02:41:04"
      - "03:16:14"
      - "03:51:23"
  - riderId: "loris_vergier"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=l9fhFQYd6N8&ab_channel=GoProBike"
    splits:
      - "00:00:15"
      - "00:52:11"
      - "01:55:03"
      - "02:49:14"
      - "03:26:20"
      - "04:03:10"
  - riderId: "myriam_nicole"
    trackId: "val_di_sole_2024"
    url: "https://www.youtube.com/watch?v=wxmaA02ymB4&ab_channel=GoProBike"
    splits:
      - "00:04:15"
      - "01:02:06"
      - "02:14:10"
      - "03:16:04"
      - "04:00:05"
      - "04:41:05"